language: node_js
node_js:
  - "node"

cache: yarn

notifications:
  email: false

services:
  - docker

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker build -t ffviii .
  - bash ./scripts/travis_docker.sh